branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Commitlint
          - ESLint
          - Prettier
          - build
          - TypeScript
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: true
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      allow_direct_pushes: true

  - name: dev
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Commitlint
          - ESLint
          - Prettier
          - build
          - TypeScript
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: true
      restrictions: null
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

allow_squash_merge: true
allow_rebase_merge: true
allow_merge_commit: true
